PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>

select distinct ?s ?o where {
?s a dbo:Species.
bind( if (exists {[] dbo:genus ?s}, "genus", 
      if (exists {[] dbo:kingdom ?s}, "kingdom",
      if (exists {[] dbo:species ?s}, "species",
      if (exists {[] dbo:phylum ?s}, "phylum",
      if (exists {[] dbo:classis ?s}, "classis",
      if (exists {[] dbo:order ?s}, "order",
      if (exists {[] dbo:family ?s}, "family",
       if (exists {?s dbo:genus []}, "species",
	"")))))))) as ?o )
}

