PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>

select distinct ?s ?o where {
?s a dbo:Species.
?o a dbo:Species.
{?s dbo:genus ?o.}
UNION{?s dbo:kingdom ?o.}
UNION{?s dbo:species ?o.}
UNION{?s dbo:phylum ?o.}
UNION{?s dbo:classis ?o.}
UNION{?s dbo:order ?o.}
UNION{?s dbo:family ?o.}
}

